### ISSUE TITLE
Great project! 2 Things

### ISSUE THREAD

**Issue by Camel-light** [KaasSchijf/Tinder-Swiper-AI#1]
Hi, thanks for the work, it's amazing :)
Two things I was not able to fix are the refresh token, after some time ~ 50 swipes, it starts bugging and returns invalid token. Is it some sort of ban from Tinder, should we set earlier delays? I noticed after 2 hours it sleeps for 300 minutes.

Any advice in which direction to look to retrain/adjust the model? It does good choices, but some outliers are really outliers :)
Great work again to revive this.

**Comment by yarodevuci** [comment]
@Camel-light have you figure it out?

**Comment by KaasSchijf** [comment]
To retrain/adjust the model look at the https://github.com/joelbarmettlerUZH/auto-tinder project.

U can change the sleep time in the code on line 278 in Modules/tinder.py

Will be looking into why refreshing the token isn't working as intended.

**Comment by KaasSchijf** [comment]
> Hi, thanks for the work, it's amazing :) Two things I was not able to fix are the refresh token, after some time ~ 50 swipes, it starts bugging and returns invalid token. Is it some sort of ban from Tinder

Fixed the refreshtoken error, try it out and let me know if it works on your end.

**Comment by yarodevuci** [comment]
@KaasSchijf how many images were used to train the classifier ?
